Fix va-table screen reader not announcing sort
department-of-veterans-affairs/component-library pull request #1433
Opened 2024-12-11 19:09 UTC by ataker

## Chromatic

https://{{head.ref}}--65a6e2ed2314f7b8f98609d8.chromatic.com

## Description
Closes [Table sorting - screen reader not announcing on sort #3538](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3538)

## QA Checklist
- [ ] Component maintains 1:1 parity with design mocks
- [ ] Text is consistent with what's been provided in the mocks
- [ ] Component behaves as expected across breakpoints
- [ ] Accessibility expert has signed off on code changes (if applicable. If not applicable provide reason why)
- [ ] Designer has signed off on changes (if applicable. If not applicable provide reason why)
- [ ] Tab order and focus state work as expected
- [ ] Changes have been tested against screen readers (if applicable. If not applicable provide reason why)
- [ ] New components are covered by e2e tests; updates to existing components are covered by existing test suite
- [ ] Changes have been tested in vets-website using Verdaccio (if applicable. If not applicable provide reason why)

## Screenshots

## Acceptance criteria
- [ ] QA checklist has been completed
- [ ] Screenshots have been attached that cover desktop and mobile screens

## Definition of done
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

2024-12-13 19:48 UTC, Andrew565 approved these changes
Clever solution!

2024-12-17 16:16 UTC, rsmithadhoc commented
I'm currently doing testing on this. I think it may work, but I was getting some inconsistency with getting it to read out on Safari. I believe it is due to Safari doing things a bit slower than Chrome. I'll try a few things on my end and test it on Windows as well.

2024-12-17 17:46 UTC, rsmithadhoc requested changes
@ataker The solution looks good, thanks for digging into this one. I'm proposing a slight tweak, but let me know if you see any issues with that.

I tested this with slow/fast voice in VoiceOver and a larger table.
- Voice speed didn't seem to affect anything.
- I found that as the table got larger, the timeout needed to be increased. The original 100ms with the current Storybook example didn't always work. But once I increased that, it worked 100% of the time.
    - 500ms supports 100 rows, so I think that is sufficient for now. It shouldn't impact the user experience, since there are things that need to be read out prior to reading out the SR text, which 500ms should be plenty. I think supporting 100 rows is sufficient, but if not we may need to look at only running `updateSRtext` after sorting has fully completed in a future update.
- I also tested in Chrome/JAWS and Firefox/NVDA and it announced as expected there.

Thanks!

2024-12-17 17:46 UTC, rsmithadhoc commented on packages/web-components/src/components/va-table/va-table-inner/va-table-inner.tsx
> +          },100)
Update to 500

2024-12-17 20:03 UTC, ataker commented on packages/web-components/src/components/va-table/va-table-inner/va-table-inner.tsx
> +          },100)
Thanks Ryan! Updated.

2024-12-17 20:14 UTC, rsmithadhoc approved these changes

2024-12-17 20:26 UTC, merged