Added an optional message to the SegmentedProgressBar in order to mat…
department-of-veterans-affairs/component-library pull request #176
Opened 2021-09-21 15:49 UTC by stiehlrod

## Description
Added an optional message to the SegmentedProgressBar in order to match the  h2 in consumerOnboarding productionAccess. The objective is to get the screen reader to read the same header that is displayed visually. All tests are passing.

Will help to close [API-9709](https://vajira.max.gov/browse/API-9709)

## Testing done
Ran npm test and all tests passed.

## Screenshots
n/a

## Acceptance criteria
n/a

## Definition of done
- [?] Documentation has been updated, if applicable
if documentation is needed, please direct me to where this should happen. thanks!
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
[Issue-548](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/548)

2021-09-21 17:19 UTC, bkjohnson requested changes
From the linked issue:

> Add an optional message to the SegmentedProgressBar in order to match the h2 in consumerOnboarding productionAccess. The objective is to get the screen reader to read the same header that is displayed visually.


The `optionalMessage` is not rendered, and it is not clear how this would solve the problem. Screenshots would be appreciated as well. Until this PR is ready, I recommend switching it into a draft PR

2021-09-22 20:11 UTC, mjlumetta reviewed
changes to the component look good! have some comments about the tests and cleaning up the comments a bit

2021-09-23 21:50 UTC, bkjohnson commented on src/components/SegmentedProgressBar/SegmentedProgressBar.jsx
> +  ariaLabel,
I _think_ this is possible, [according to the docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters#earlier_parameters_are_available_to_later_default_parameters).

```suggestion
  ariaLabel = `Step ${current} of ${total}`,
```

2021-09-23 21:50 UTC, bkjohnson commented on src/components/SegmentedProgressBar/SegmentedProgressBar.jsx
> +      aria-label={ariaLabel || `Step ${current} of ${total}`}
And then this could just use the prop:

```suggestion
      aria-label={ariaLabel}
```

2021-09-23 22:43 UTC, bkjohnson reviewed
Also @noahgelman, does this look OK in terms of a11y?

2021-09-27 16:53 UTC, bkjohnson approved these changes
This looks good to me, and I don't _think_ there are any a11y issues. Noah may have more insight, but I don't want to block this.

2021-09-28 13:57 UTC, merged