Issue 32630
department-of-veterans-affairs/component-library pull request #238
Opened 2021-12-07 20:01 UTC by tmac9494

## Description
Closes 32630
forces border-box property on banner and removes some unnecessary padding between content and button. Also adds a max-width of 100vw as a safe measure

## Testing done
tested locally, fixed ios issue

2021-12-07 21:44 UTC, k80bowman commented
@tmac9494 I'd like to have some more details and screenshots on this PR, please. Also, it looks like it has some changes that were from your [previous pr](https://github.com/department-of-veterans-affairs/component-library/pull/215). @bkjohnson and I had asked a question on that, but never heard back from you. I'd like to get that PR merged first, so that we're not merging in those changes with this PR.

2021-12-07 21:44 UTC, k80bowman requested changes

2021-12-07 21:44 UTC, k80bowman commented on packages/web-components/src/components/va-alert/va-alert.css
> +  box-sizing: border-box !important;
I'd rather we not use the `!important` declaration here.

2021-12-08 20:50 UTC, tmac9494 commented
> @tmac9494 I'd like to have some more details and screenshots on this PR, please. Also, it looks like it has some changes that were from your [previous pr](https://github.com/department-of-veterans-affairs/component-library/pull/215). @bkjohnson and I had asked a question on that, but never heard back from you. I'd like to get that PR merged first, so that we're not merging in those changes with this PR.

sorry that was my mistake, I'll fix the bad merge and provide screenshots today

2022-04-08 14:50 UTC, pdavies88 commented
@tmac9494 are these CSS changes still needed for the `va-alert` component? This PR has been open for awhile without any movement I would like to close it if changes are no longer required. Alternatively feel free to submit a bug ticket and we can prioritize the work for an upcoming sprint: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/new/choose

2022-04-12 19:26 UTC, pdavies88 commented
@tmac9494 I am going to close this PR if you would like to have us make some changes please submit a ticket and we will prioritize. Link for ticket submission: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/new/choose

2022-04-12 19:26 UTC, closed without merging