ProgressBar and LoadingIndicator axe fixes
department-of-veterans-affairs/component-library pull request #28
Opened 2021-02-04 14:56 UTC by ddzz

## Description
This PR adds default `aria-label` values to the `ProgressBar`, `SegmentedProgressBar`, and `LoadingIndicator`. This fixes axe failures caused by an `aria-label` value not being set for these components.

Closes two tickets: [`ProgressBar` axe failure](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/357) and [`LoadingIndicator` axe failure](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/366).

## Testing done
- No failures observed when running the axe browser plugin on pages that use these components.
- Ran the entire Cypress test suite locally using these changes. No axe failures observed for any `ProgressBar`s or `LoadingIndicator`s.

## Acceptance criteria
- [ ] No axe failures seen in the axe browser plugin for pages that use these components
- [ ] No axe failures in the `vets-website` Cypress test suite.

2021-02-08 17:21 UTC, bkjohnson reviewed
I'll let Trevor weigh in on this one, since I'm not sure if those are the defaults that we want.

2021-02-09 22:12 UTC, 1Copenut requested changes
@ddzz Thank you for putting this together so quickly. I pulled your branch locally and used the `file:../` import in package.json to work with it briefly. I was getting good results and no axe-core errors. Just a few text changes and I'll retest and we should be ready to ship.

2021-02-09 22:12 UTC, 1Copenut commented on src/components/LoadingIndicator/LoadingIndicator.jsx
> +  label: "loading-indicator",
Let's change this to just read "Loading". I've been chatting with @jbalboni and @noahgelman about possible fast-follow improvements for this component using a role="status" and requiring a `{message}` prop. That's out of the scope for this ticket, and they're still reviewing it in VAOS. Having this label gets this PR to where we need it, with axe-core errors cleaned up and plain language for the spinner.

2021-02-10 17:27 UTC, 1Copenut commented on src/components/SegmentedProgressBar/SegmentedProgressBar.jsx
> +      aria-label={`Step ${current} of ${total}`}
I looked more closely this morning for instances of `<SegmentedProgressBar />` to make sure we wouldn't introduce trouble upstream. I found only three, and no instances were passing in a `{label}` prop. The most pertinent one was [line 83 of FormNav.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/9c610f8981da2b3608af0e4bc10519072d78d158/src/platform/forms-system/src/js/components/FormNav.jsx#L83). I think this is a good solution, and definitely could be iterated on down the road.

2021-02-10 17:36 UTC, 1Copenut approved these changes
👍 LGTM! I'll write two follow on tickets for out of scope improvements discovered during this PR review cycle. Thank you @ddzz !

2021-02-10 18:10 UTC, bkjohnson approved these changes
:+1:

2021-02-10 18:39 UTC, merged