41424 Storybook Introduction Page Links
department-of-veterans-affairs/component-library pull request #458
Opened 2022-06-10 15:56 UTC by pdavies88

## Chromatic

https://{{head.ref}}--60f9b557105290003b387cd5.chromatic.com

## Description
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/41425

## Screenshots
<img width="743" alt="Screen Shot 2022-06-10 at 11 55 27 AM" src="https://user-images.githubusercontent.com/11822533/173104735-ed187ba0-cdb6-45a4-bd4d-b2fdab77455a.png">

## Acceptance criteria
- [X] Sections and links are created for the pages listed above on the [Introduction page](https://design.va.gov/storybook/?path=/docs/about-introduction--page)

## Definition of done
- [ ] Documentation has been updated, if applicable
- [X] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

2022-06-10 21:01 UTC, k80bowman commented on packages/storybook/stories/introduction.stories.mdx
> +</strong>
```suggestion
<strong>
  <a
    href="https://design.va.gov/about/developers#using-the-design-system"
    target="_blank"
  >
    Implement and install the design system on your project.
  </a>
</strong>
```

Not sure about what this looks like with the `<strong>` tag, but check it out and see what you think. I'm not keen on the "link here" text, I'd rather have the links in context. I also prefer declarative statements here, so please update the following two to match this one.

2022-06-10 21:01 UTC, k80bowman commented on packages/storybook/stories/introduction.stories.mdx
> +The maturity scale indicates the level of maturity of each component and pattern in the system. It helps designers and developers know if they can use the component and what level of caution they sho
```suggestion
The maturity scale indicates the level of maturity of each component and pattern in the system. It helps designers and developers know if they should use the component and what level of caution they should have when doing so.
```

2022-06-10 21:02 UTC, k80bowman requested changes
Please see comments above.

2022-06-13 15:39 UTC, k80bowman commented
Thank you for making the updates, Preston. Just one more question, why do the new links look different than the "how to use Storybook" link? If there is a way to make these new ones look like that one (with the darker blue and the underline) that would be great.

![image](https://user-images.githubusercontent.com/12739849/173391501-848db081-502b-4235-9401-91a6f1bc8303.png)

2022-06-13 16:09 UTC, k80bowman commented
@andresriveratoro @pdavies88 It looks like that issue was taken care of in #437  (as noted in the ticket). Preston, if this fix did not fix the links in this PR, it looks like some additional work may be necessary.

2022-06-13 16:30 UTC, pdavies88 commented
@k80bowman I added some CSS to `.sbdocs-a` which gets generated when creating storybook pages with .mdx so now all links look the same. Screenshot here:
<img width="605" alt="Screen Shot 2022-06-13 at 12 28 07 PM" src="https://user-images.githubusercontent.com/11822533/173401140-890e337d-8559-4554-8ab0-bea25508c7cd.png">

2022-06-13 19:25 UTC, merged