Add "On this page" component
department-of-veterans-affairs/component-library pull request #59
Opened 2021-03-15 21:42 UTC by bkjohnson

## Description
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/20620

This adds the `<va-on-this-page>` Web Component.

## Testing done

Local storybook

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

2021-03-16 22:26 UTC, bkjohnson commented on .storybook/preview.js
> +import '@department-of-veterans-affairs/formation/dist/formation';
This is purely for local dev.

2021-03-16 22:26 UTC, bkjohnson commented on package.json
> +    "@department-of-veterans-affairs/formation": "^6.14.0",
This allows us to get some of the familiar styles (fonts, etc.) in our Storybook environment.

2021-03-16 22:26 UTC, bkjohnson commented on src/mixins/links.css
> +a {
This is in a mixin file because I expect we may have other components with links in the shadow DOM, and we can just `@import` this when we get there.

2021-03-17 13:08 UTC, k80bowman requested changes
the changes here all look good, but you may need to do a rebase. I noticed when I checked out your branch and ran storybook that there were only three components in the src directory.

2021-03-17 22:06 UTC, k80bowman approved these changes

2021-04-01 21:26 UTC, bkjohnson commented
The previous two commits are for the staging review feedback: https://github.com/department-of-veterans-affairs/va.gov-team/issues/21957

2021-04-02 19:17 UTC, merged