60122 va select inert
department-of-veterans-affairs/component-library pull request #716
Opened 2023-06-12 17:00 UTC by rhasselle-oddball

## Chromatic

https://60122-va-select-inert--60f9b557105290003b387cd5.chromatic.com

## Description
- department-of-veterans-affairs/va.gov-team#60122
- additional context in this slack thread: https://dsva.slack.com/archives/C01DBGX4P45/p1686238079010729

## Testing done
- Tested in chrome with usdws true and false (will apply to both)
- yarn tests
- Tested in IE11 mode in Edge - did not work perfectly (but I think it's because the options weren't showing up at all, which may be unrelated to inert). Do we need full backward compatibility here?

Questions: 
- Do we need a new storybook example for inert? or is it OK to just include the CSS?
- Do we need a new property for inert? or simply having the CSS is fine when the user passes the native `inert` property?

```
  <va-select
    aria-live-region-text="You selected"
    hint="This is a hint"
    label="Branch of Service"
    name="branch"
    value="navy"
    inert
    usdws
  >
    <option value="navy">
      Navy
    </option>
    <option value="army">
      Army
    </option>
    <option value="marines">
      Marines
    </option>
    <option value="air-force">
      Air Force
    </option>
    <option value="coastguard">
      Coastguard
    </option>
  </va-select>
```

## Screenshots
without inert, usdws
![image](https://github.com/department-of-veterans-affairs/component-library/assets/123402053/afdb2c70-f199-4b45-82ba-dc1c71f366bf)

with inert, usdws
![image](https://github.com/department-of-veterans-affairs/component-library/assets/123402053/666774df-1e0a-48cf-b2ad-4a200296c444)

## Acceptance criteria
- [x] added new css
- [ ] do i need to add a new storybook example or use case?

## Definition of done
- [ ] Documentation has been updated, if applicable - do I need to update any documentation?
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

2023-06-12 17:13 UTC, Andrew565 commented
I think adding a storybook story would be a really good idea, there’s no better way for other people to be made aware that this option exists otherwise. Because it’s a native attribute, I don’t think you need to spell it out as a separate property.

2023-06-14 15:30 UTC, rhasselle-oddball commented
one discovery is that when using inert, the label also becomes unclickable/selectable. not sure if that will be a deal breaker or not.

2023-06-14 19:08 UTC, rhasselle-oddball commented on packages/storybook/stories/va-select-uswds.stories.jsx
> +        inert
this is same as Template above, but just added this property.

2023-06-14 19:52 UTC, Andrew565 requested changes

2023-06-14 19:52 UTC, Andrew565 commented on packages/web-components/src/index.html
> +    <va-select
Can you undo this change to the index.html file please? Just confusing.

2023-06-14 20:11 UTC, Andrew565 approved these changes

2023-06-14 20:13 UTC, merged