va-radio, va-radio-option: Screen reader and keyboard navigation updates
department-of-veterans-affairs/component-library pull request #860
Opened 2023-09-20 21:11 UTC by powellkerry

## Chromatic

https://{{head.ref}}--60f9b557105290003b387cd5.chromatic.com

## Description
- Remove tabIndex from radio options. They were causing options to be read as a "group"
- Update input Ids so they don't conflict with the web-component element id. This was causing the screen reader to not read the option label
- Change va-radio-option from `shadow: true` to `shadow: false`. This was causing the screen reader to not announce the total number of options and dictate that each option was its own radio group
- Remove label `id` attribute as this is not used and was causing AXE checks to complain about duplicate ids
- Update CSS to work with not having a host/shadow root
- Update tests for changes to HTML and functionality being tied to the input and not the web-component
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2075

## Testing done
- Local testing in Chrome, Safari, Firefox and Edge
- Screen reader testing done with Mac VoiceOver

## Screenshots
v1 Before:
![Screenshot 2023-09-20 at 3 07 36 PM](https://github.com/department-of-veterans-affairs/component-library/assets/1776069/01593d16-aa63-498b-8693-a7df7885e0b3)

v1 After:
![Screenshot 2023-09-20 at 3 08 13 PM](https://github.com/department-of-veterans-affairs/component-library/assets/1776069/28ca56b4-a3bb-4f1f-b606-59f25da1f481)

v3 Before:
![Screenshot 2023-09-20 at 3 08 44 PM](https://github.com/department-of-veterans-affairs/component-library/assets/1776069/c4a89af1-1d5f-4729-a1f7-c8cfee808067)

v3 After:
![Screenshot 2023-09-20 at 3 09 25 PM](https://github.com/department-of-veterans-affairs/component-library/assets/1776069/78e771b3-ab72-42d9-924c-61e95638608b)

## Acceptance criteria
- [ ] Component works as before functionally
- [ ] Criteria found in card by @rsmithadhoc are met

## Definition of done
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

2023-09-20 21:28 UTC, powellkerry commented
There is a difference in appearance between before and after v3 versions, working on hunting that down.

2023-09-21 16:38 UTC, powellkerry commented
tabIndex was just introduced in the last release. We need to make sure that this change does not introduce a regression. See: https://github.com/department-of-veterans-affairs/component-library/pull/786

2023-09-21 18:02 UTC, rsmithadhoc requested changes
@powellkerry Thanks for picking this up, this worked perfectly for me with keyboard and screen reader. However, I left a comment for the focus style not using the VA yellow.

Thanks!

2023-09-21 20:59 UTC, powellkerry commented on packages/web-components/src/components/va-radio-option/va-radio-option.scss
>  }
This should be fixed. Removing the shadow on the options caused a bunch of small things like this, prior to that the USWDS version was probably inheriting that style from the previous version.

2023-09-22 14:49 UTC, rsmithadhoc approved these changes
Looks good, thanks!

2023-09-22 15:07 UTC, merged